# Generated by Django 3.0.4 on 2020-03-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RickyM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
